language: ruby
script:
  - bundle exec rake test:db:create
  - bundle exec rspec spec
rvm:
  2.2.0
matrix:
  include:
    - env:
      - DB_TYPE=mysql
      - DB_USERNAME=travis
    - env:
      - DB_TYPE=postgres
