language: ruby
before_install:
  - gem install bundler
script:
  - bundle exec rake test:db:create
  - bundle exec rspec spec
  - if [ "$RUN_BENCHMARK" = "true" ]; then DATASET_SIZE=100 bundle exec rake benchmark; fi
rvm:
  2.2.0
matrix:
  include:
    - env:
      - DB_TYPE=mysql
      - DB_USERNAME=travis
    - env:
      - DB_TYPE=postgres
      - RUN_BENCHMARK=true
